name: Python Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: |
        import requests
        from datetime import datetime

        url = 'http://transito.gtrans.com.br/cttupe/index.php/portal/getImg/192.168.10.105/'

        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")

        response = requests.get(url)
        with open(f'imagem_{timestamp}.png', 'wb') as file:
            file.write(response.content)
        print(f'imagem_{timestamp}.png criada')

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Add new image"
        git push
